// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXtCV9nSb21bGa87YCfYeEV3uqEtxA2F4',
    appId: '1:608922232112:web:580a65a92a4df22cead4f5',
    messagingSenderId: '608922232112',
    projectId: 'e-commerce-webapp-7da7f',
    authDomain: 'e-commerce-webapp-7da7f.firebaseapp.com',
    storageBucket: 'e-commerce-webapp-7da7f.appspot.com',
    measurementId: 'G-4E30NQ37JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2hddd20IBFUZp1j7qr5j1oKc-DyfkepA',
    appId: '1:608922232112:android:ccf86754509444f5ead4f5',
    messagingSenderId: '608922232112',
    projectId: 'e-commerce-webapp-7da7f',
    storageBucket: 'e-commerce-webapp-7da7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM_PkcvtaXYyBUiWGEuIpPSmpXBLyAs9I',
    appId: '1:608922232112:ios:05347f4fe95c99b6ead4f5',
    messagingSenderId: '608922232112',
    projectId: 'e-commerce-webapp-7da7f',
    storageBucket: 'e-commerce-webapp-7da7f.appspot.com',
    iosClientId: '608922232112-cpilem8qavlepl2cseb9phci17e31554.apps.googleusercontent.com',
    iosBundleId: 'com.rafiqul.ecom.eCommerceWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM_PkcvtaXYyBUiWGEuIpPSmpXBLyAs9I',
    appId: '1:608922232112:ios:05347f4fe95c99b6ead4f5',
    messagingSenderId: '608922232112',
    projectId: 'e-commerce-webapp-7da7f',
    storageBucket: 'e-commerce-webapp-7da7f.appspot.com',
    iosClientId: '608922232112-cpilem8qavlepl2cseb9phci17e31554.apps.googleusercontent.com',
    iosBundleId: 'com.rafiqul.ecom.eCommerceWebapp',
  );
}
